name: CI Tests

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:

  basic_checks:
    name: Basic environment and code checks / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
      - name: Python info
        run: |
          which python
          python --version
      - name: Show pip list
        run: |
          pip list
